services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_streamvault
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      GLIBC_TUNABLES: "glibc.pthread.rseq=1"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express_streamvault
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/"
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
    depends_on:
      - mongodb
    restart: unless-stopped

  webvowl:
    image: d1egoprog/webvowl:latest
    container_name: webvowl_visualizer
    ports:
      - "${WEBVOWL_PORT}:8080"
    restart: unless-stopped

  app:
    build: .
    container_name: streamvault_app
    user: "1000:1000"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
    volumes:
      - .:/app
    depends_on:
      - mongodb
    restart: "no"

  loki:
    image: grafana/loki:latest
    container_name: loki_streamvault
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki
    restart: unless-stopped

  promtail:
    image: grafana/promtail:latest
    container_name: promtail_streamvault
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - loki
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_streamvault
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - loki
    restart: unless-stopped

volumes:
  mongo_data:
  loki_data:
  grafana_data: