server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki_streamvault:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'
      
      - source_labels: ['__meta_docker_container_name']
        regex: '/streamvault_app.*'
        target_label: 'service'
        replacement: 'app'
      - source_labels: ['__meta_docker_container_name']
        regex: '/mongo_express_streamvault.*'
        target_label: 'service'
        replacement: 'database-admin'
      - source_labels: ['__meta_docker_container_name']
        regex: '/mongodb_streamvault.*'
        target_label: 'service'
        replacement: 'database'
      - source_labels: ['__meta_docker_container_name']
        regex: '/webvowl_visualizer.*'
        target_label: 'service'
        replacement: 'visualizer'